notifications:
    email:
        on_success: change
        on_failure: change
language: minimal
env:
    global:
        - DOCKER_COMPOSE_VERSION=1.23.0
        - SSH_DEPLOY_KEY_PATH=./app/Resources/deploy/deploy_key
        - DEPLOY_SERVER_HOST=vps632104.ovh.net
services:
    - docker
stages:
    - test
    - deploy
jobs:
    include:
#        -   stage: deploy
#            if: branch = master
#            name: deploy
#            before_install:
#                - openssl aes-256-cbc -K $encrypted_05beada88e3a_key -iv $encrypted_05beada88e3a_iv
#                    -in ${SSH_DEPLOY_KEY_PATH}.enc -out ${SSH_DEPLOY_KEY_PATH} -d
#                - eval "$(ssh-agent -s)"
#                - chmod 600 ${SSH_DEPLOY_KEY_PATH}
#                - echo -e "Host ${DEPLOY_SERVER_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#                - cat ~/.ssh/config
#                - ssh-add ${SSH_DEPLOY_KEY_PATH}
#            script:
#                - ssh -i ${SSH_DEPLOY_KEY_PATH} root@${DEPLOY_SERVER_HOST} "echo 'Connected, Hello !!!! '; hostname"
#                - scp -i ${SSH_DEPLOY_KEY_PATH} app/Resources/deploy/deploy.sh root@${DEPLOY_SERVER_HOST}:deploy.sh
#                - ssh -i ${SSH_DEPLOY_KEY_PATH} root@${DEPLOY_SERVER_HOST} "bash deploy.sh"
