version: '3.5'

services:
    nginx-proxy:
        container_name: proxy
        image: jwilder/nginx-proxy
        networks:
            - network-proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
networks:
    network-proxy:
        name: network-proxy